/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import clases.Validate;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

 
public class Ejercicio_1 extends javax.swing.JDialog {
   
    
    private Integer Anio;
    
    private Integer AnioActual;
    
    private Integer Edad;
    
    private String FechaNacimiento_;
    
    private String NamePersona;
    
    DefaultTableModel model;
    
    Validate valida = new Validate();
    /**
     * Creates new form Ejercicio_1
     */
    public Ejercicio_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setTitle("Aplicación que calcula la edad");
        
        this.setLocationRelativeTo(null);
        
        model = (DefaultTableModel)Tabla_Resgistro.getModel();
        
                /// personalizar jtable
        
        Tabla_Resgistro.getTableHeader().setBackground(Color.red);
        
        Tabla_Resgistro.getTableHeader().setForeground(Color.white);
        
        Tabla_Resgistro.setRowHeight(35);
        
        Tabla_Resgistro.getTableHeader().setPreferredSize(new Dimension(120,40));
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamePersona = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Resgistro = new javax.swing.JTable();
        btnCalcular = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ingrese Nombre de la persona  :  ");

        jLabel2.setText("Seleccione fecha de nacimiento  :  ");

        FechaNacimiento.setDateFormatString("dd/MM/yyyy");
        FechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Tabla_Resgistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PERSONA", "FECHA NACIMIENTO", "EDAD"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Resgistro);
        if (Tabla_Resgistro.getColumnModel().getColumnCount() > 0) {
            Tabla_Resgistro.getColumnModel().getColumn(0).setMinWidth(200);
            Tabla_Resgistro.getColumnModel().getColumn(0).setMaxWidth(450);
            Tabla_Resgistro.getColumnModel().getColumn(1).setMinWidth(200);
            Tabla_Resgistro.getColumnModel().getColumn(1).setMaxWidth(400);
            Tabla_Resgistro.getColumnModel().getColumn(2).setMinWidth(60);
            Tabla_Resgistro.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        btnCalcular.setText("Calcular edad  ");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamePersona)
                            .addComponent(FechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnNuevo)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
        
      if(txtNamePersona.getText().isEmpty())
      {
       txtNamePersona.grabFocus();
      }else
      {
        if(FechaNacimiento.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fecha de nacimiento","¡ADVERTENCIA!",JOptionPane.WARNING_MESSAGE);
        }else{
            getEdad();
        }
      }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    reset();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      reset();
      /// limpiamos todo registro de la 
      valida.ClearTable(model);
    }//GEN-LAST:event_btnNuevoActionPerformed
 
    private void getEdad()
    {
        /// obtenemos la fecha de nacimiento a string
        FechaNacimiento_ =((JTextField)FechaNacimiento.getDateEditor().getUiComponent()).getText();
        
        NamePersona = txtNamePersona.getText(); /// obtenemos los nombres de la persona
        
        Anio = FechaNacimiento.getCalendar().get(Calendar.YEAR); /// obtenemos el año de la fecha seleccionado
        
        ///obtenemos la fecha actual
     
        Date  FechaActual = new Date(); 
      
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        formato.format(FechaActual);
        
        AnioActual =formato.getCalendar().get(Calendar.YEAR);
        
        
        /// proceso para calcular la edad
      
        Edad = AnioActual-Anio;
        
        /// validamos la existencia por nombre de la persona
        
        if(!valida.Exist(Tabla_Resgistro, NamePersona, 0)){
         
            // agregamos a la tabla
         addTable(NamePersona,FechaNacimiento_,Edad);
        
        }else
        {
           JOptionPane.showMessageDialog(null, "Esa persona ya esta registrada","Mensaje del sistema",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void addTable(String Persona,String FechaNac,Integer Edad_)
    {
        Object PersonaData[] = {Persona,FechaNac,String.valueOf(Edad_)+" años"};
        
        model.addRow(PersonaData);
        
    }
    
    private void reset()
    {
      txtNamePersona.setText("");
      FechaNacimiento.setDate(null);
      
      txtNamePersona.grabFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ejercicio_1 dialog = new Ejercicio_1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private javax.swing.JTable Tabla_Resgistro;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNamePersona;
    // End of variables declaration//GEN-END:variables
}
